Models/Recipe.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;

namespace OatBoySystem.Models;

public class Recipe
{
    [Key]
    public int RecipeId { get;set; }

    [Required]
    public string Name { get;set; }

    public string Description { get;set; }

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    public List<Product> Products { get;set; } = new();
    public List<RecipeBakingMaterialAssociation> BakingMaterialAssociations { get;set; } = new();
    public List<Batch> Batches { get;set; } = new();

}

Models/ViewModels/BatchAddStockForm.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using OatBoySystem.Models;
namespace OatBoySystem.Models.ViewModels;
public class BatchAddStockForm
{
    public int BatchId { get;set; }
    public int BakingMaterialStockId { get;set; }
    public List<BakingMaterialStock> RelatedStock { get;set; } = new();
    [BakingMaterialInstock]
    public int Quantity { get;set; }
    public int Needed { get;set; }
}

public class BakingMaterialInstockAttribute : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        if (value == null)
        {
            return new ValidationResult("Quantity is required");
        }
        OatBoyContext _context = (OatBoyContext)validationContext.GetService(typeof(OatBoyContext));
        BatchAddStockForm data = (BatchAddStockForm)validationContext.ObjectInstance;
        BakingMaterialStock BMStock = _context.BakingMaterialStock.FirstOrDefault(bms => bms.BakingMaterialStockId == data.BakingMaterialStockId);
        if (BMStock == null)
        {
            return new ValidationResult("Baking material not found");
        }
        if (BMStock.Quantity < data.Quantity)
        {
            return new ValidationResult("Stock too low");
        }
        if (data.Needed < data.Quantity)
        {
            return new ValidationResult("Quantity more than needed");
        }
        else
        {
            return ValidationResult.Success;
        }
    }
}

Controllers/BakeryController.cs
#pragma warning disable CS8600
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using OatBoySystem.Models;
using OatBoySystem.Models.ViewModels;

namespace OatBoySystem.Controllers;

[Route("bakery")]
public class BakeryController : Controller
{
    private readonly ILogger<BakeryController> _logger;

    private OatBoyContext _context;

    private Dictionary<int, string> BatchStatus = new Dictionary<int, string>()
    {
        {0,"Ordered"},
        {1,"In Process"},
        {2,"Cooling"},
        {3,"Drying"},
        {4,"Ready To Pack"},
        {5,"Processed"},
        {6,"Quarantine"},
        {7,"Recall"},
    };


    public BakeryController(ILogger<BakeryController> logger, OatBoyContext context)
    {
        _logger = logger;
        _context = context;
    }

    //RECIPES
    [HttpGet("recipes")]
    public ViewResult Recipes()
    {
        List<Recipe> AllRecipes = _context.Recipes.Include(r => r.Batches).ToList();
        return View("Recipes", AllRecipes);
    }

    [HttpPost("recipes/create")]
    public IActionResult RecipeCreate(Recipe newRecipe)
    {
        if (!ModelState.IsValid)
        {
            return Recipes();
        }
        _context.Add(newRecipe);
        _context.SaveChanges();
        return RedirectToAction("RecipeView", new { rId = newRecipe.RecipeId });
    }

    [HttpGet("recipes/{rId}")]
    public ViewResult RecipeView(int rId)
    {
        Recipe Recipe = _context.Recipes
                            .Include(r => r.BakingMaterialAssociations)
                            .ThenInclude(bma => bma.BakingMaterial)
                            .FirstOrDefault(r => r.RecipeId == rId);
        List<BakingMaterial> AllBakingMaterials = _context.BakingMaterials.ToList();
        RecipeEdit ViewModel = new() { Recipe = Recipe, AllBakingMaterials = AllBakingMaterials };
        return View("RecipeView", ViewModel);
    }

    [HttpPost("recipes/{rId}/add_ingredient")]
    public IActionResult RecipeAddIngredient(int rId, RecipeAddIngredient formModel)
    {
        if (!ModelState.IsValid)
        {
            var message = string.Join(" | ", ModelState.Values
                                .SelectMany(v => v.Errors)
                                .Select(e => e.ErrorMessage));
            Console.WriteLine(message);

            return RecipeView(rId);
        }
        RecipeBakingMaterialAssociation newAss = new()
        {
            RecipeId = rId,
            BakingMaterialId = formModel.BakingMaterialId,
            Quantity = formModel.Quantity
        };
        _context.Add(newAss);
        _context.SaveChanges();
        return RedirectToAction("RecipeView", new { rId });

    }

    [HttpPost("recipes/{rId}/{bmId}/update")]
    public IActionResult RecipeUpdateIngredient(int rId, int bmId, RecipeBakingMaterialAssociation rbma)
    {
        if (!ModelState.IsValid)
        {
            return RecipeView(rId);
        }
        RecipeBakingMaterialAssociation toUpdate = _context.RecipeBakingMaterialAssociations
                                                        .FirstOrDefault(rbma => rbma.RecipeId == rId && rbma.BakingMaterialId == bmId);
        toUpdate.Quantity = rbma.Quantity;
        _context.SaveChanges();
        return RedirectToAction("RecipeView", new { rId });

    }

    [HttpPost("recipes/{rId}/{bmId}/remove")]
    public IActionResult RecipeRemoveIngredient(int rId, int bmId)
    {
        RecipeBakingMaterialAssociation toBeRemoved = _context.RecipeBakingMaterialAssociations
                                                            .FirstOrDefault(rbma => rbma.RecipeId == rId && rbma.BakingMaterialId == bmId);
        _context.Remove(toBeRemoved);
        _context.SaveChanges();
        return RedirectToAction("RecipeView", new { rId });

    }

    [HttpGet("recipes/{rId}/all_batches")]
    public ViewResult RecipeAllBatch(int rId)
    {
        Recipe RecipeWithBatches = _context.Recipes.Include(r => r.Batches).FirstOrDefault(r => r.RecipeId == rId);
        ViewBag.Statuses = BatchStatus;
        return View("RecipeAllBatch", RecipeWithBatches);
    }

    //BATCHES

    [HttpGet("dashboard")]
    public ViewResult BakeryDashboard()
    {
        ViewBag.Statuses = BatchStatus;
        return View("BakeryDashboard", new BakeryDash()
        {
            AllRecipes = _context.Recipes.ToList(),
            AllBatches = _context.Batches.Include(b => b.Recipe).OrderByDescending(b => b.BatchId).ToList()
        });
    }

    [HttpPost("batches/create")]
    public RedirectToActionResult BatchCreate(int rId)
    {
        Batch newBatch = new() { RecipeId = rId, Status = 0 };
        _context.Add(newBatch);
        _context.SaveChanges();
        return RedirectToAction("BatchEdit", new { bId = newBatch.BatchId });
    }

    [HttpGet("batches/{bId}")]
    public ViewResult BatchEdit(int bId)
    {
        Batch toEdit = _context.Batches
                            .Include(b => b.BakingMaterialStockAssociations)
                            .ThenInclude(bmsa => bmsa.BakingMaterialStock)
                            .Include(b => b.Recipe)
                            .ThenInclude(r => r.BakingMaterialAssociations)
                            .ThenInclude(bma => bma.BakingMaterial)
                            .FirstOrDefault(b => b.BatchId == bId);

        List<BakingMaterialStock> AllBakingMaterialStock = _context.BakingMaterialStock.Include(bms => bms.BakingMaterial).Where(bms => bms.Quantity > 0).ToList();
        ViewBag.Statuses = BatchStatus;
        ViewBag.CurrentStock = AllBakingMaterialStock;
        return View("BatchEdit", toEdit);
    }

    [HttpPost("batches/{bId}/status")]
    public RedirectToActionResult BatchStatusUpdate(int bId, int status)
    {
        Batch toUpdate = _context.Batches.FirstOrDefault(b => b.BatchId == bId);
        toUpdate.Status = status;
        _context.SaveChanges();
        return RedirectToAction("BakeryDashboard");
    }

    [HttpPost("batches/{batchId}/addstock")]
    public IActionResult BatchAddStock(int batchId, BatchAddStockForm basForm)
    {
        if (!ModelState.IsValid)
        {
            var message = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
            Console.WriteLine(message);
            return BatchEdit(batchId);
        }
        Console.WriteLine($"batch {batchId} stock {basForm.BakingMaterialStockId} qty {basForm.Quantity}");
        BatchBakingMaterialStockAssociation newAss = new()
        {
            Quantity = basForm.Quantity,
            BatchId = batchId,
            BakingMaterialStockId = basForm.BakingMaterialStockId
        };
        _context.Add(newAss);
        _context.SaveChanges();
        return RedirectToAction("BatchEdit", new { bId = batchId });
    }

    [HttpPost("batches/{batchId}/{bbmsaId}/remove")]
    public IActionResult BatchRemoveStock(int batchId, int bbmsaId)
    {
        Console.WriteLine($"batch {batchId} assss {bbmsaId}");
        BatchBakingMaterialStockAssociation bbmsa = _context.BatchBakingMaterialStockAssociations
                                                        .FirstOrDefault(bbmsa => bbmsa.BatchBakingMaterialStockAssociationId == bbmsaId);
        if(bbmsa == null)
        {
            Console.WriteLine("ass not found");
            return RedirectToAction("BatchEdit", new{bId = batchId});
        }
        _context.Remove(bbmsa);
        _context.SaveChanges();
        return RedirectToAction("BatchEdit", new{bId = batchId});
        
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Views/Bakery/BakeryDashboard.cshtml
@model BakeryDash
@{
    ViewData["Title"] = "Bakery Dash";
}
<div class="container text-center">
    <h1>Bakery</h1>
    @if(Model.AllRecipes.Count == 0)
    {
        <h2>Please input recipe before baking</h2>
    }
    else
    {
    <h2>Recipe to craft:</h2>
    <form asp-action="BatchCreate" asp-controller="Bakery" method="post">
        <select name="rId">
            @foreach (Recipe recipe in Model.AllRecipes)
            {
                <option value="@recipe.RecipeId">@recipe.Name</option>
            }
        </select>
        <button class="btn btn-primary">Let's bake!</button>
    </form>
    }
    <h2>Previous Batches:</h2>
    <ul class="text-center">
    @if(Model.AllBatches.Count == 0)
    {
        <h2>You haven't baked anything yet, Mergie.</h2>
    }
    @foreach (Batch batch in Model.AllBatches)
    {
        <li class="no-dot"><a asp-action="BatchEdit" asp-controller="Bakery" asp-route-bId="@batch.BatchId">@batch.BatchId @batch.Recipe?.Name -- @ViewBag.Statuses[batch.Status]</a></li>
    }
    </ul>
</div>

Views/Bakery/BatchEdit.cshtml
@model Batch
@{
    ViewData["Title"] = Model.Recipe.Name;
}
<div class="container text-center">
    <h1>Batch Admin</h1>
    <p>@Model.Recipe?.Name @Model.BatchId</p>
    <form class="d-flex align-items-center gap-3" asp-action="BatchStatusUpdate" asp-controller="Bakery" asp-route-bId="@Model.BatchId">
        <label >Status:</label>
        <select name="status">
            @foreach (KeyValuePair<int,string> kvp in ViewBag.Statuses)
            {
                if (kvp.Key == Model.Status)
                {
                    <option value="@kvp.Key" selected>@kvp.Value</option>
                } else 
                {
                    <option value="@kvp.Key" >@kvp.Value</option>
                }
            }
        </select>
        <button class="btn btn-primary">Update</button>
    </form>

    @foreach (RecipeBakingMaterialAssociation rbma in Model.Recipe.BakingMaterialAssociations)
    {
        List<BatchBakingMaterialStockAssociation> matched = Model.BakingMaterialStockAssociations.Where(bmsa => bmsa.BakingMaterialStock.BakingMaterialId == rbma.BakingMaterialId).ToList();
        int added = matched.Sum(bmsa => bmsa.Quantity );
        int needed = rbma.Quantity - added;
        List<BakingMaterialStock> AllStock = ViewBag.CurrentStock;
        List<BakingMaterialStock> corelated = AllStock.Where(bms=> bms.BakingMaterialId == rbma.BakingMaterialId).ToList();
        
        <p class="text-start mt-3">@rbma.BakingMaterial.Name @added / @rbma.Quantity @rbma.BakingMaterial.UnitOfMeasure.ToUpper() filled </p>
        <div class="container">
            @foreach (BatchBakingMaterialStockAssociation bbmsa in matched)
            {
                <div class="d-flex justify-content-center align-items-center gap-2 mb-5">

                <label>@bbmsa.BakingMaterialStock.Brand (@bbmsa.BakingMaterialStock.Batch) -- @bbmsa.Quantity @rbma.BakingMaterial.UnitOfMeasure.ToUpper()</label>
                <form asp-action="BatchRemoveStock" asp-controller="Bakery" method="Post" asp-route-batchId="@Model.BatchId" asp-route-bbmsaId="@bbmsa.BatchBakingMaterialStockAssociationId">
                    <button class="btn btn-danger">X</button>
                </form>
                </div>
            }

            <div>
                @if (corelated.Count > 0 )
                {   
                    if (needed > 0)
                    {
                        @await Html.PartialAsync("_BatchAddStockForm", new BatchAddStockForm(){BatchId=Model.BatchId, RelatedStock=corelated,Needed=needed});
                    }
                    else
                    {
                        <p>Item filled</p>
                    }
                } else {
                    <p>No stock available</p>
                }
            </div>
        </div>
    }
    <div class="my-5">😍</div>
</div>

Views/Bakery/RecipeAllBatch.cshtml
@model Recipe
@{
    ViewData["Title"] = "Batch by Recipe";
}
<div class="container text-center">
    <h1>@Model.Name</h1>
<ul>
    @foreach (Batch batch in Model.Batches)
    {
        <li class="no-dot"><a asp-action="BatchEdit" asp-controller="Bakery" asp-route-bId="@batch.BatchId">@batch.BatchId
                @batch.Recipe?.Name -- @ViewBag.Statuses[batch.Status]</a></li>
    }
</ul>
</div>

Views/Bakery/RecipeView.cshtml
@model RecipeEdit
@{
    ViewData["Title"] = Model.Recipe.Name;
    List<BakingMaterial> Unassociated = Model.AllBakingMaterials.Where(bm => bm.RecipeAssociations.All(ra => ra.RecipeId !=
    Model.Recipe.RecipeId)).ToList();
}
<div class="text-center container">
    <h1>@Model.Recipe.Name</h1>
    <p>@Model.Recipe.Description</p>
    <h2>Ingredients:</h2>
    @if (Model.Recipe.BakingMaterialAssociations.Count == 0)
    {
        <p>Please add ingredients to recipe</p>
    }
    @foreach (RecipeBakingMaterialAssociation rcbma in Model.Recipe.BakingMaterialAssociations)
    {
        @await Html.PartialAsync("_UpdateIngredient", rcbma)
    }
    <h2>Add Ingredient:</h2>
    @if (Unassociated.Count > 0)
    {
        @await Html.PartialAsync("_AddIngredient",new RecipeAddIngredient(){Unassociated = Unassociated,RecipeId=Model.Recipe.RecipeId});  
    } else if (Model.Recipe.BakingMaterialAssociations.Count == 0)
    {
        <p>No ingredients in system, please input ingredients</p>
    }
    else 
    {
        <p>All ingredients on recipe</p>
    }


</div>

Views/Bakery/Recipes.cshtml
@model List<Recipe>
@{
    ViewData["Title"] = "Recipes";
}
<div class="text-center container">
    @if (Model.Count == 0)
    {
        <h2>No recipes yet, create one below 👇</h2>
    }
    else
    {
        <h1>Recipes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Batches</th>
                </tr>
            </thead>
            <tbody>
                    @foreach (Recipe r in Model)
                    {
                    <tr>
                        <td><a asp-action="RecipeView" asp-controller="Bakery" asp-route-rId="@r.RecipeId">@r.Name</a></td>
                        <td><a asp-action="RecipeAllBatch" asp-controller="Bakery" asp-route-rId="@r.RecipeId">@r.Batches.Count</a></td>
                    </tr>
                    }
            </tbody>
        </table>
    }
    @await Html.PartialAsync("_RecipeNew", new Recipe())
</div>

Views/Bakery/_AddIngredient.cshtml
@model RecipeAddIngredient

<form asp-action="RecipeAddIngredient" asp-controller="Bakery"  asp-route-rId="@Model.RecipeId" method="Post" class="d-flex justify-content-center align-items-center gap-2 w-100 flex-wrap">
    <select asp-for="BakingMaterialId">
        @foreach (BakingMaterial bm in Model.Unassociated)
        {
            <option value="@bm.BakingMaterialId">@bm.Name (@bm.UnitOfMeasure.ToUpper())</option>
        }
    </select>
    <input asp-for="Quantity">
    <p><span asp-validation-for="Quantity" class="text-danger"></span></p>
    <button class="btn btn-primary">Submit</button>
</form>

Views/Bakery/_BatchAddStockForm.cshtml
@model BatchAddStockForm

<form asp-action="BatchAddStock" asp-controller="Bakery" method="Post" asp-route-batchId="@Model.BatchId">
    <input type="hidden" asp-for="Needed" value="@Model.Needed">
    <select asp-for="BakingMaterialStockId">
        @foreach (BakingMaterialStock bms in Model.RelatedStock)
        {
            <option value="@bms.BakingMaterialStockId">@bms.Brand (@bms.Batch) -- @bms.Quantity avail</option>
        }
    </select>
    <input type="number" asp-for="Quantity">
    <button class="btn btn-primary">+</button>
    <p class="text-danger"><span asp-validation-for="Quantity"></span></p>
</form>

Views/Bakery/_RecipeNew.cshtml
@model Recipe

<h2>New Recipe</h2>
<form asp-action="RecipeCreate" asp-controller="Bakery" method="Post">
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name">
        <p><span class="text-danger" asp-validation-for="Name"></span></p>
    </div>
    <div class="mb-3">
        <label asp-for="Description"></label>
        <input asp-for="Description">
        <p><span class="text-danger" asp-validation-for="Description"></span></p>
    </div>
    <button class="btn btn-primary">Create</button>
</form>

Views/Bakery/_UpdateIngredient.cshtml
@model RecipeBakingMaterialAssociation
<div class="d-flex justify-content-between align-items-center gap-2 w-100 mb-4">
    <form asp-action="RecipeUpdateIngredient" asp-controller="Bakery" asp-route-rId="@Model.RecipeId"
        asp-route-bmId="@Model.BakingMaterialId" method="Post"
        class="d-flex justify-content-between align-items-center gap-2 w-100">
        <p class="w-25">@Model.BakingMaterial.Name</p>
        <input asp-for="Quantity" value=@Model.Quantity class="w-25">
        <p class="w-25">@Model.BakingMaterial.UnitOfMeasure.ToUpper()</p>
        <p><span asp-validation-for="Quantity" class="text-danger"></span></p>
        <button class="btn btn-primary">Update</button>
    </form>
    <form asp-action="RecipeRemoveIngredient" asp-controller="Bakery" asp-route-rId="@Model.RecipeId"
        asp-route-bmId="@Model.BakingMaterialId" method="Post" class="d-flex justify-content-between align-items-center">
        <button class="btn btn-danger">X</button>
    </form>
</div>